config/routes.rb
Rails.application.routes.draw do
  
mount Ckeditor::Engine => '/ckeditor'
mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'

Athingwithfeathers::Application.routes.draw do

  #mount Ckeditor::Engine => '/ckeditor'
  resources :channels do
    resources :pins
  end

  get "/pins/:id/repost" => "pins#repin_new", as: 'repin_new'
  post "/pins/:id/repost" => "pins#repin_create", as: 'repin_create'

  get "/users/:id/block_user" => "users#block_user_new", as: 'block_user_new'
  post "/users/:id/block_user" => "users#block_user_create", as: 'block_user_create'


  devise_for :users,  controllers: { registrations: "users/registrations" }

  root "pages#_home"
  get "about" => "pages#about"
  get "love" => "pages#love"
  get "goal-setting-prompts" => "pages#goal-setting-prompts"
  get "heal-with-forgiveness" => "pages#heal-with-forgiveness"
  get "how-to-figure-out-what-you-want" => "pages#how-to-figure-out-what-you-want"
  get "drop-out-of-school" => "pages#drop-out-of-school"
  get "recommended-reading" => "pages#recommended-reading"
  get "self-sabotage" => "pages#self-sabotage"
  get "negativity-detox" => "pages#negativity-detox"
  get "figure-out-your-life" => "pages#figure-out-your-life"
  get "slow-it-down" => "pages#slow-it-down"
  get "negativity-detox-success" => "pages#negativity-detox-success"
  get "foyl-success" => "pages#foyl-success"
  get "/sign_up"   => "devise/registrations#new"
  get "/privacy-policy"   => "pages#privacy-policy"
  get "thank-you" => "pages#thank-you", as: :thank_you
  
  # My Channels
  resources :users
  #get '/users/:id' => 'users#show'

  #mount Commontator::Engine => '/commontator'
  
  get "resources", to: "resources#resources"
  resources :articles, only: [:index, :show]
  resources :courses, only: [:index, :show]

end
end

app/models/channel.rb
class Channel < ActiveRecord::Base
	belongs_to :user

  has_many :pins, dependent: :destroy

  has_attached_file :image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :image

  def self.my_channels(user)
    Channel.where("user_id = ?", user.id)
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]

  # GET /channels
  # GET /channels.json
  def index
    if user_signed_in?
      #only pull channels with pins
      @pin_channels = Channel.joins(:pins).uniq
      # show only channels from unblocked users
      @channels = @pin_channels.where.not(user_id: current_user.blocks.pluck(:blocked_user_id))
    else
      @channels = Channel.joins(:pins).uniq
    end    
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @pins = @channel.pins
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end
  
  # POST /channels
  # POST /channels.json
  def create
    @channel = current_user.channels.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @channel }
      else
        format.html { render action: 'new' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:name, :description, :image)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div class="main-container">
  <header class="signup">
    <div class="background-image-holder parallax-background">
      <img class="background-image" alt="Background Image" src="/images/browse.jpg">
    </div>

    <div class="container text-center">
      <div class="row text-center">
        <div class="col-sm-12 text-center">
          <h1 class="text-white">Browse</h1>
         <% if user_signed_in? %>
          <span class="text-white">Get our weekly inspirational emails, and a love letter: "You're Not Broken."</span><br><br>
          <div id="mc_embed_signup"> <form class="validate" id="mc-embedded-subscribe-form" action="//resilientapp.us9.list-manage.com/subscribe/post?u=0f2ed3ea91eb1d8f12d344ee1&amp;id=4334a5a58c" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank"> <div class="mc-field-group"> <input class="required" id="mce-FNAME" type="text" name="FNAME" placeholder="First Name" value=""  /> <input class="required email" id="mce-EMAIL" type="email" name="EMAIL" placeholder="Email Address" value=""  /> <input type="hidden" name="b_8c2fdee11f59dc4d7adf9bcbf_83dec78335" value=""><input type="submit" id="mc-embedded-subscribe" /> </div> </form>
     <% else %>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-white btn-primary" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-filled" %>
  <% end %> 
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <h1>Editing channel</h1>

    <%= render 'form' %>

    <%= link_to 'Back', channels_path %>
  </div>
</div>

app/views/channels/index.html.erb
<div class="main-container">
  <header class="signup">
      <div class="background-image-holder parallax-background">
        <img class="background-image" alt="Background Image" src="/images/browse.jpg">
      </div>

      <div class="container text-center">
        <div class="row text-center">
          <div class="col-sm-12 text-center">
            <h1 class="text-white">Browse</h1>
            <span class="text-white">Free inspirational and positive pictures to make you happy! :)</span>
          </div>
        </div>
      </div>
  </header>

  <div class="container"><br>

    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Resilient Main -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-4579984495238903"
     data-ad-slot="9304520911"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script><br><br>

    <div id="pins" class="transitions-enabled">

      <% @channels.each do |channel| %>
        <div class="col-md-3">
          <%= link_to channel do %>
            <div class="channel_box">
              <% if channel.image? %>
                <span><%= image_tag channel.image.url(:medium) %></span>
              <% elsif channel.pins.first %>
                <span><%= image_tag channel.pins.first.image.url(:medium) %></span>  
              <% end %>
            </div>
            <div class="channel_footer">
              <hr style="margin: 10px 0">
              <h4><%= channel.name %></h4>
              <%= channel.description.truncate(60) %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

</div>

app/views/channels/new.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div class="main-container">
  <header class="signup">
    <div class="background-image-holder parallax-background">
      <img class="background-image" alt="Background Image" src="/images/browse.jpg">
    </div>

    <div class="container text-center">
      <div class="row text-center">
        <div class="col-sm-12 text-center">
          <h1 class="text-white"><%= @channel.name %>New Channel</h1>
         <% if user_signed_in? %>
          <span class="text-white">Get our weekly inspirational emails, and a love letter: "You're Not Broken."</span><br><br>
          <div id="mc_embed_signup"> <form class="validate" id="mc-embedded-subscribe-form" action="//resilientapp.us9.list-manage.com/subscribe/post?u=0f2ed3ea91eb1d8f12d344ee1&amp;id=4334a5a58c" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank"> <div class="mc-field-group"> <input class="required" id="mce-FNAME" type="text" name="FNAME" placeholder="First Name" value=""  /> <input class="required email" id="mce-EMAIL" type="email" name="EMAIL" placeholder="Email Address" value=""  /> <input type="hidden" name="b_8c2fdee11f59dc4d7adf9bcbf_83dec78335" value=""><input type="submit" id="mc-embedded-subscribe" /> </div> </form>
     <% else %>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-white btn-primary" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-filled" %>
  <% end %> 
        </div>
      </div>
    </div>
  </header>
  <div class="container"><br><br>

    Channels are different categories that you can post things in.   You could create a channel for calming down, a happy channel, a funny channel, a bad day toolbox, etc.  You can make multiple channels, and they all go on your profile page.<br><br>

    <%= render 'form' %>

    <%= link_to 'Back', channels_path %>
  </div>
</div>

<br><br><div class="text-center"><a href="/resources"><img src="/images/classes-ad.jpg"></a></div><br><br>

</div></div>

app/views/channels/show.html.erb
<% if current_user %>
  <% @pins.each do |pin|%>
  <div aria-hidden="false" aria-labelledby="myModalLabel" class="modal fade" id="new-repin-modal-<%= pin.id %>" role="dialog" tabindex="-1">
    <% @pin = pin %>
    <%= render partial: '/pins/repin_new_modal' %>
  </div>
  <% end %>
<% end %>

<div class="main-container">
  <header class="signup">
    <div class="background-image-holder parallax-background">
      <img class="background-image" alt="Background Image" src="/images/browse.jpg">
    </div>

    <div class="container text-center">
      <div class="row text-center">
        <div class="col-sm-12 text-center">
          <h1 class="text-white"><%= @channel.name %></h1>
          <span class="text-white"><%= @channel.description %></span>
        </div>
      </div>

    </div>
  </header>

  <p id="notice"><%= notice %></p>

  <div class="container">

    <%= link_to 'Back', channels_path %> |
    <% if @channel.user == current_user %>
      <%= link_to 'Edit', edit_channel_path(@channel) %> |
      <%= link_to 'Delete', channel_path(@channel), data: {:confirm => 'Are you sure you want to delete this pin?'}, method: :delete %>
    <% end %><br><br>

    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Resilient Main -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-4579984495238903"
     data-ad-slot="9304520911"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

<br><br><div class="text-center"><a href="http://classes.resilientapp.com/"><img src="/images/classes-ad.jpg"></a></div><br><br>

    <div class="row"></div>
    <% if @channel.user == current_user %>
      <div class="col-md-3">
        <%= link_to new_channel_pin_path(@channel) do %>
          <div class="new_channel_box">
            Add Pin <br />
            <i class="fa fa-plus-circle fa-2x"></i>
          </div>
        <% end %>
      </div>
    <% end %>

    <div id="pins" class="transitions-enabled">
            <% @pins.each do |pin| %>
        <div class="col-md-3">
          <div class="repin_box">
          <% if pin.user != current_user && user_signed_in? %>
            <%= link_to "javascript:void(0)", class: 'repin_link', data: { target: "#new-repin-modal-#{pin.id}", toggle: "modal"} do %>
              <i class="fa fa-heart repin pull-left"> Save</i>
            <% end %>
          <% end %>
          </div>
          <%= link_to channel_pin_path(pin.channel, pin) do %>
            <div class="channel_box">
              <span><%= image_tag pin.image.url(:medium) %></span>
            </div>
           <div class="channel_footer">
              <hr>
              <%= pin.description.truncate(60) %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <br><br><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Resilient Main -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-4579984495238903"
     data-ad-slot="9304520911"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

  </div>
</div>