config/routes.rb
Rails.application.routes.draw do
  
mount Ckeditor::Engine => '/ckeditor'
mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'

Athingwithfeathers::Application.routes.draw do

  #mount Ckeditor::Engine => '/ckeditor'
  resources :channels do
    resources :pins
  end

  get "/pins/:id/repost" => "pins#repin_new", as: 'repin_new'
  post "/pins/:id/repost" => "pins#repin_create", as: 'repin_create'

  get "/users/:id/block_user" => "users#block_user_new", as: 'block_user_new'
  post "/users/:id/block_user" => "users#block_user_create", as: 'block_user_create'


  devise_for :users,  controllers: { registrations: "users/registrations" }

  root "pages#_home"
  get "about" => "pages#about"
  get "love" => "pages#love"
  get "goal-setting-prompts" => "pages#goal-setting-prompts"
  get "heal-with-forgiveness" => "pages#heal-with-forgiveness"
  get "how-to-figure-out-what-you-want" => "pages#how-to-figure-out-what-you-want"
  get "drop-out-of-school" => "pages#drop-out-of-school"
  get "recommended-reading" => "pages#recommended-reading"
  get "self-sabotage" => "pages#self-sabotage"
  get "negativity-detox" => "pages#negativity-detox"
  get "figure-out-your-life" => "pages#figure-out-your-life"
  get "slow-it-down" => "pages#slow-it-down"
  get "negativity-detox-success" => "pages#negativity-detox-success"
  get "foyl-success" => "pages#foyl-success"
  get "/sign_up"   => "devise/registrations#new"
  get "/privacy-policy"   => "pages#privacy-policy"
  get "thank-you" => "pages#thank-you", as: :thank_you
  
  # My Channels
  resources :users
  #get '/users/:id' => 'users#show'

  #mount Commontator::Engine => '/commontator'
  
  get "resources", to: "resources#resources"
  resources :articles, only: [:index, :show]
  resources :courses, only: [:index, :show]

end
end

app/models/article.rb
class Article < Resource
  extend FriendlyId
end

app/models/block.rb
class Block < ActiveRecord::Base
	belongs_to :user

	validates :user_id, :blocked_user_id, presence: true
	validates_uniqueness_of :user_id, scope: :blocked_user_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user

   has_many :pins
end

app/models/channel.rb
class Channel < ActiveRecord::Base
	belongs_to :user

  has_many :pins, dependent: :destroy

  has_attached_file :image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :image

  def self.my_channels(user)
    Channel.where("user_id = ?", user.id)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :pin
end

app/models/course.rb
class Course < Resource
  extend FriendlyId
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  belongs_to :channel
  has_attached_file :image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :image

  validates :image, presence: true
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged 

  has_attached_file :preview_image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :preview_image

  scope :default_order, -> { order(priority: :desc) }
  scope :enabled, -> { where(disabled: false) }
  scope :top, -> { default_order.limit 10 }
end

app/models/resource_page.rb
class ResourcePage < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged 

  has_attached_file :preview_image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }

  scope :default_order, -> { order(order: :asc) }
  scope :enabled, -> { where(disabled: false) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
  has_many :channels
  has_many :blocks

  has_attached_file :image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :image

  validates :name, presence: true

  # Callbacks
  after_create :add_to_mailing_list

  def admin?;admin;end
  private
  def add_to_mailing_list
    Mailchimp::AddToMailingList.subscribe(self)
  end
end

def forem_name
  name
end

app/controllers/articles_controller.rb
class ArticlesController < ResourcesController
end

app/controllers/courses_controller.rb
class CoursesController < ResourcesController
end

app/controllers/forem_controller.rb
class ForemController < ApplicationController
  def base
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    # protect_from_forgery
    before_action :set_pin, only: [:show, :edit, :update, :destroy]
    #before_action :correct_user, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    def index
       @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    end

    def show
      @channel = Channel.find(params[:channel_id])
    end

    def new
        @channel = Channel.find(params[:channel_id])
        @pin = @channel.pins.new
        @pin.user = current_user
    end

    def edit
      @channel = Channel.find(params[:channel_id])
      @pin = Pin.find(params[:id])
    end

    def create
        @channel = Channel.find(params[:channel_id])
        @pin = @channel.pins.new(pin_params)
        @pin.user = current_user
        if @pin.save
          redirect_to channel_pin_path(@channel, @pin), notice: 'Pin was successfully created.'
        else
          render action: 'new'
        end
    end

    def repin_new
      @pin = params[:id]
      @repin = Pin.new
    end

    def repin_create
      pin = Pin.find_by(id: params[:id])
      channel_id = params["pin"]["channel_id"]
      channel = Channel.find_by(id: channel_id)
      repin = pin.dup
      repin.user = current_user
      repin.channel = channel
      repin.image = pin.image
      # respond_to do |format|
        if repin.save
          # format.js { render }
          flash[:notice] = "Your pin was saved to #{channel.name}"
          redirect_to :back
        end
      # end
    end

    def update
        if @pin.update_attributes(pin_params)
            redirect_to channel_pin_path(@pin.channel, @pin), notice: 'Pin was successfully updated.'
        else
           render action: 'edit'
        end
    end

    def destroy
        @channel = Channel.find(params[:channel_id])
        if @pin.destroy
          redirect_to channel_path(@channel)
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
    def set_pin
        @pin = Pin.find(params[:id])
    end

    def correct_user
        @pin = current_user.pins.find_by(id: params[:id])
        redirect_to channel_pin_path(@pin.channel), notice: "Not authorized to edit this pin" if @pin.nil?
    end

    def pin_params
      params.require(:pin).permit(:description, :image, :image_url)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:destroy]

  # GET /users/dan
  def show
    @user = User.find_by(id: params[:id])
    @channels = @user.channels.order("created_at DESC")
	end

	def block_user_new
		@block = Block.new
	end

	def block_user_create
		@block = Block.new
		@block.user_id = params[:block][:user_id]
		@block.blocked_user_id = params[:block][:blocked_user_id]
		if @block.save
			redirect_to channels_path, notice: 'This User has been blocked'
		else
			redirect_to :back, notice: "You have already blocked this User."
		end	
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forem_helper.rb
module ForemHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= form_for @pin, url: channel_pins_path(@channel), html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :image_url, 'Source' %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


app/views/pins/_repin_new_modal.html.erb
<%= form_for @pin, url: repin_create_path(@pin), method: :post, :authenticity_token => true do |f| %>
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Save</h4>
      </div>

      <div class="modal-body">
        Please choose the channel you wish to save to.

          <%= f.collection_select :channel_id, Channel.my_channels(current_user).order(:name),:id, :name, class:"form-control", include_blank: true %>

      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Submit', class: 'btn btn-default' %>
        <!--<button type="button" class="btn btn-primary">Save changes</button>-->
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
<% end %>

app/views/pins/edit.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div class="main-container">
  <header class="signup">
    <div class="background-image-holder parallax-background">
      <img class="background-image" alt="Background Image" src="/images/browse.jpg">
    </div>

    <div class="container text-center">
      <div class="row text-center">
        <div class="col-sm-12 text-center">
          <h1 class="text-white"><%= @channel.name %></h1>
        </div>
      </div>
    </div>
  </header>
  <p id="notice"><%= notice %></p>

  <div class="container">

    <%= form_for @pin, url: channel_pin_path(@channel, @pin), html: { multipart: true } do |f| %>
      <% if @pin.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

          <ul>
            <% @pin.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
      </div>

      <div class="field">
        <%= f.label :image_url, 'Image Url' %><br>
        <%= f.text_field :image_url %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>


    <%= link_to 'Back', channel_pin_path(@channel, @pin) %>


  </div>
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div class="main-container">
      <header class="signup"> 
          <div class="background-image-holder parallax-background">
            <img class="background-image" alt="Background Image" src="/images/home.jpg">
          </div>
          
          <div class="container text-center">
              <div class="row text-center">
                <div class="col-sm-12 text-center">
                  <h1 class="text-white">Browse</h1>
                  <span class="text-white">Free inspirational and positive pictures to make you happy! :)</span>
                </div>
              </div>
            </div><!--end of container-->
      </header>

      <div class="main-container">
        <div class="row">
          <div class="col-md-1">
            &nbsp;
          </div>
            <div class="col-md-10 row-offset-1 row-offset-2">

              <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Resilient Main -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-4579984495238903"
     data-ad-slot="9304520911"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script><br>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %><br/>
        <strong><%= pin.user.email if pin.user %></strong>
        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to 'Edit', edit_pin_path(pin) %>
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

<br>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Resilient Main -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-4579984495238903"
     data-ad-slot="9304520911"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script><br>

</div>
</div>
</div>

</div>

app/views/pins/new.html.erb
<div class="main-container">
      <header class="signup"> 
          <div class="background-image-holder parallax-background">
            <img class="background-image" alt="Background Image" src="/images/browse.jpg">
          </div>
          
          <div class="container text-center">
              <div class="row text-center">
                <div class="col-sm-12 text-center">
                  <h1 class="text-white">New Pin</h1>
         <% if user_signed_in? %>
         <span class="text-white">Get our weekly inspirational emails, and a love letter: "You're Not Broken."</span><br><br>
          <div id="mc_embed_signup"> <form class="validate" id="mc-embedded-subscribe-form" action="//resilientapp.us9.list-manage.com/subscribe/post?u=0f2ed3ea91eb1d8f12d344ee1&amp;id=4334a5a58c" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank"> <div class="mc-field-group"> <input class="required" id="mce-FNAME" type="text" name="FNAME" placeholder="First Name" value=""  /> <input class="required email" id="mce-EMAIL" type="email" name="EMAIL" placeholder="Email Address" value=""  /> <input type="hidden" name="b_8c2fdee11f59dc4d7adf9bcbf_83dec78335" value=""><input type="submit" id="mc-embedded-subscribe" /> </div> </form>
     <% else %>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-white btn-primary" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-filled" %>
  <% end %> 
                </div>
              </div>
            </div><!--end of container-->
      </header>

     <div class="main-container">
        <div class="row">
          <div class="col-md-1">
            &nbsp;
          </div>
            <div class="col-md-10 row-offset-1 row-offset-2">

              Keep the posts positive, related to mental health, and recovery-focused.  Please do not post anything potentially triggering or negative.<br><br>

<%= render 'form' %>

<%= link_to 'Back', channel_path(@channel) %>

</div></div></div>

<br><br><div class="text-center"><a href="/resources"><img src="/images/classes-ad.jpg"></a></div><br><br>

</div>

app/views/pins/repin_create.js.erb
$('#new-repin-modal').modal('hide');
$('#repin_link').attr("disabled", true)
$('.repin').removeClass('fa fa-heart')
$('.repin').text(" Saved!")

app/views/pins/repin_new.js.erb
$("#new-repin-modal").html("#{<%= j render partial: 'repin_new_modal' %>}");
$("#new-repin-modal").modal('show');

app/views/pins/show.html.erb
<!--<div aria-hidden="true" aria-labelledby="myModalLabel" class="modal fade" id="new-repin-modal" role="dialog" tabindex="-1"></div>-->
<!--<div aria-hidden="true" aria-labelledby="myModalLabel" class="modal fade" id="new-repin-modal" role="dialog" tabindex="-1"></div>-->
<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script> -->
<% if current_user %>
  <div aria-hidden="false" aria-labelledby="myModalLabel" class="modal fade" id="new-repin-modal" role="dialog" tabindex="-1">
    <%= render partial: '/pins/repin_new_modal' %>
  </div>
<% end %>
<div class="main-container">
  <header class="signup">
    <div class="background-image-holder parallax-background">
      <img class="background-image" alt="Background Image" src="/images/browse.jpg">
    </div>

    <div class="container text-center">
      <div class="row text-center">
        <div class="text-center">
          <h1 class="text-white">View Pin</h1>
        </div>
      </div>
    </div>
  </header>
  <p id="notice"><%= notice %></p>

  <div class="container">

    <%= link_to 'Back', channel_path(@channel) %>


    <div class="row">
      <div class="col-md-offset-2 col-md-8">

        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Resilient Main -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-4579984495238903"
     data-ad-slot="9304520911"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script><br>


        <div class="panel panel-default">
          <div class="panel-heading center">
            <% if @pin.user != current_user && user_signed_in? %>
              <%= link_to "javascript:void(0)", :data => {toggle: "modal", target: "#new-repin-modal", id: 'repin_link'} do %>
                <i class="fa fa-heart repin pull-left"> Save</i>
              <% end %>
            <% end %>
            <% if @pin.image_url.present? %>
              <%= link_to @pin.image_url, target: "_blank" do %>
                <%= image_tag @pin.image.url(:large), class:"center-block" %>
              <% end %>
            <% else %>
              <%= image_tag @pin.image.url(:large), class:"center-block" %>
            <% end %>
          </div>
          <div class="panel-body">
            <p><strong>Description: </strong><%= @pin.description %></p>
            <% if @pin.image_url? %>
              <p><strong>URL: </strong><%= link_to @pin.image_url do %>
                <span> <%= @pin.image_url %></span>
              <% end %>
              </p>
            <% end %>
            
            <strong>Created by: <%= link_to(@pin.user.name, user_path(@pin.user)) if @pin.user %></strong>
            <div class="dropdown">
                <i id="flag" class="fa fa-flag pull-right" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </i>
                <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dLabel">
                  <li class="flag_link">
                    <%= mail_to "katie@resilientapp.com", "Intellectual Property?", subject: "Intellectual Property - Channel: #{@channel.id}, Pin: #{@pin.id}", body: "www.resilientapp.com#{channel_pin_path}, Pin Author: #{@pin.user.email}"   %>
                  </li>
                  <li class="flag_link">
                    <%= mail_to "katie@resilientapp.com", "Flag Pin", subject: "Flagged Pin - Channel: #{@channel.id}, Pin: #{@pin.id}", body: "www.resilientapp.com#{channel_pin_path},  Pin Author: #{@pin.user.email}"   %>
                  </li>
                </ul>
            </div>

            <% if @pin.user == current_user %>
              <%= link_to "Edit", edit_channel_pin_path(@channel, @pin) %> |
              <%= link_to 'Delete', channel_pin_path(@channel, @pin), data: {:confirm => 'Are you sure you want to delete this pin?'}, method: :delete %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

     <br><div class="text-center"><strong>If you like this pin, please share it with your friends!  Spread the word about Resilient. :)</strong>
   </div>

<div class='shareaholic-canvas' data-app='share_buttons' data-app-id='13081882'></div>

<br><br><div class="text-center"><a href="http://classes.resilientapp.com/"><img src="/images/classes-ad.jpg"></a></div><br><br>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Resilient Main -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-4579984495238903"
     data-ad-slot="9304520911"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

</div>
</div>
</div>
  </div>
</div>