config/routes.rb
Rails.application.routes.draw do
  
mount Ckeditor::Engine => '/ckeditor'
mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'

Athingwithfeathers::Application.routes.draw do

  #mount Ckeditor::Engine => '/ckeditor'
  resources :channels do
    resources :pins
  end

  get "/pins/:id/repost" => "pins#repin_new", as: 'repin_new'
  post "/pins/:id/repost" => "pins#repin_create", as: 'repin_create'

  get "/users/:id/block_user" => "users#block_user_new", as: 'block_user_new'
  post "/users/:id/block_user" => "users#block_user_create", as: 'block_user_create'


  devise_for :users,  controllers: { registrations: "users/registrations" }

  root "pages#_home"
  get "about" => "pages#about"
  get "love" => "pages#love"
  get "goal-setting-prompts" => "pages#goal-setting-prompts"
  get "heal-with-forgiveness" => "pages#heal-with-forgiveness"
  get "how-to-figure-out-what-you-want" => "pages#how-to-figure-out-what-you-want"
  get "drop-out-of-school" => "pages#drop-out-of-school"
  get "recommended-reading" => "pages#recommended-reading"
  get "self-sabotage" => "pages#self-sabotage"
  get "negativity-detox" => "pages#negativity-detox"
  get "figure-out-your-life" => "pages#figure-out-your-life"
  get "slow-it-down" => "pages#slow-it-down"
  get "negativity-detox-success" => "pages#negativity-detox-success"
  get "foyl-success" => "pages#foyl-success"
  get "/sign_up"   => "devise/registrations#new"
  get "/privacy-policy"   => "pages#privacy-policy"
  get "thank-you" => "pages#thank-you", as: :thank_you
  
  # My Channels
  resources :users
  #get '/users/:id' => 'users#show'

  #mount Commontator::Engine => '/commontator'
  
  get "resources", to: "resources#resources"
  resources :articles, only: [:index, :show]
  resources :courses, only: [:index, :show]

end
end

app/models/article.rb
class Article < Resource
  extend FriendlyId
end

app/models/block.rb
class Block < ActiveRecord::Base
	belongs_to :user

	validates :user_id, :blocked_user_id, presence: true
	validates_uniqueness_of :user_id, scope: :blocked_user_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user

   has_many :pins
end

app/models/channel.rb
class Channel < ActiveRecord::Base
	belongs_to :user

  has_many :pins, dependent: :destroy

  has_attached_file :image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :image

  def self.my_channels(user)
    Channel.where("user_id = ?", user.id)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :pin
end

app/models/course.rb
class Course < Resource
  extend FriendlyId
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  belongs_to :channel
  has_attached_file :image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :image

  validates :image, presence: true
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged 

  has_attached_file :preview_image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :preview_image

  scope :default_order, -> { order(priority: :desc) }
  scope :enabled, -> { where(disabled: false) }
  scope :top, -> { default_order.limit 10 }
end

app/models/resource_page.rb
class ResourcePage < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged 

  has_attached_file :preview_image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }

  scope :default_order, -> { order(order: :asc) }
  scope :enabled, -> { where(disabled: false) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
  has_many :channels
  has_many :blocks

  has_attached_file :image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :image

  validates :name, presence: true

  # Callbacks
  after_create :add_to_mailing_list

  def admin?;admin;end
  private
  def add_to_mailing_list
    Mailchimp::AddToMailingList.subscribe(self)
  end
end

def forem_name
  name
end

app/controllers/courses_controller.rb
class CoursesController < ResourcesController
end

app/controllers/forem_controller.rb
class ForemController < ApplicationController
  def base
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    # protect_from_forgery
    before_action :set_pin, only: [:show, :edit, :update, :destroy]
    #before_action :correct_user, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    def index
       @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    end

    def show
      @channel = Channel.find(params[:channel_id])
    end

    def new
        @channel = Channel.find(params[:channel_id])
        @pin = @channel.pins.new
        @pin.user = current_user
    end

    def edit
      @channel = Channel.find(params[:channel_id])
      @pin = Pin.find(params[:id])
    end

    def create
        @channel = Channel.find(params[:channel_id])
        @pin = @channel.pins.new(pin_params)
        @pin.user = current_user
        if @pin.save
          redirect_to channel_pin_path(@channel, @pin), notice: 'Pin was successfully created.'
        else
          render action: 'new'
        end
    end

    def repin_new
      @pin = params[:id]
      @repin = Pin.new
    end

    def repin_create
      pin = Pin.find_by(id: params[:id])
      channel_id = params["pin"]["channel_id"]
      channel = Channel.find_by(id: channel_id)
      repin = pin.dup
      repin.user = current_user
      repin.channel = channel
      repin.image = pin.image
      # respond_to do |format|
        if repin.save
          # format.js { render }
          flash[:notice] = "Your pin was saved to #{channel.name}"
          redirect_to :back
        end
      # end
    end

    def update
        if @pin.update_attributes(pin_params)
            redirect_to channel_pin_path(@pin.channel, @pin), notice: 'Pin was successfully updated.'
        else
           render action: 'edit'
        end
    end

    def destroy
        @channel = Channel.find(params[:channel_id])
        if @pin.destroy
          redirect_to channel_path(@channel)
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
    def set_pin
        @pin = Pin.find(params[:id])
    end

    def correct_user
        @pin = current_user.pins.find_by(id: params[:id])
        redirect_to channel_pin_path(@pin.channel), notice: "Not authorized to edit this pin" if @pin.nil?
    end

    def pin_params
      params.require(:pin).permit(:description, :image, :image_url)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    thank_you_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:destroy]

  # GET /users/dan
  def show
    @user = User.find_by(id: params[:id])
    @channels = @user.channels.order("created_at DESC")
	end

	def block_user_new
		@block = Block.new
	end

	def block_user_create
		@block = Block.new
		@block.user_id = params[:block][:user_id]
		@block.blocked_user_id = params[:block][:blocked_user_id]
		if @block.save
			redirect_to channels_path, notice: 'This User has been blocked'
		else
			redirect_to :back, notice: "You have already blocked this User."
		end	
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forem_helper.rb
module ForemHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/users/show.html.erb
<div class="main-container">
  <header class="signup">
    <div class="background-image-holder parallax-background">
      <img class="background-image" alt="Background Image" src="/images/forms.jpg">
    </div>

    <div class="container text-center">
      <div class="row text-center">
        <div class="col-sm-12 text-center">
          <% if @user.image? %>
          <%= image_tag @user.image.url(:thumb), alt: @user.name, class: 'profile-image' %>
          <% end %>
          <h1 class="text-white">Profile</h1>
         <% if user_signed_in? %>
     <% else %>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-white btn-primary" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-filled" %>
  <% end %> 
        </div>
      </div>
    </div>
  </header>

  <div class="container"><br><br>

    <div class="center userShow">
      
      <h1>
        My Channels:

        <% if user_signed_in? && current_user != @user %>
          <div class="dropdown pull-right">
            <i id="blockFlag" class="fa fa-flag pull-right" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dLabel">
              <li class="flag_link">
                  <%= mail_to "katie@resilientapp.com", "Report User", subject: "Report User", body: "www.resilientapp.com#{user_path} Username: #{@user.name}, User E-mail: #{@user.email}"   %>
              </li>
              <li class="flag_link">
                <%= form_for Block.new, url: block_user_create_path,:html => {:id => "blockForm"}, method: :post, :authenticity_token => true do |f| %>
                        
                  <%= f.hidden_field :user_id, value: current_user.id %>
                  <%= f.hidden_field :blocked_user_id, value: @user.id %>
                        
                  <% f.submit 'Block User' %>
                <% end %>
                <a id="blockUser">Block User</a>
              </li>
            </ul>
          </div>
        <% end %>  
      </h1>
      
  </div>

    <% if user_signed_in? %>
      <div class="col-md-3">
        <%= link_to new_channel_path do %>
          <div class="new_channel_box">
            Add Channel <br />
            <i class="fa fa-plus-circle fa-2x"></i>
          </div>
        <% end %>
      </div>
    <% end %>

    <div id="pins" class="transitions-enabled">

      <% @channels.each do |channel| %>
        <div class="col-md-3">
          <%= link_to channel do %>
            <div class="channel_box">
              <% if channel.image? %>
                <span><%= image_tag channel.image.url(:medium) %></span>
              <% end %>

            </div>
            <div class="channel_footer">
              <hr style="margin: 10px 0">
              <h4><%= channel.name %></h4>
              <%= channel.description.truncate(60) %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

</div>