config/routes.rb
Rails.application.routes.draw do
  
mount Ckeditor::Engine => '/ckeditor'
mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'

Athingwithfeathers::Application.routes.draw do

  #mount Ckeditor::Engine => '/ckeditor'
  resources :channels do
    resources :pins
  end

  get "/pins/:id/repost" => "pins#repin_new", as: 'repin_new'
  post "/pins/:id/repost" => "pins#repin_create", as: 'repin_create'

  get "/users/:id/block_user" => "users#block_user_new", as: 'block_user_new'
  post "/users/:id/block_user" => "users#block_user_create", as: 'block_user_create'


  devise_for :users,  controllers: { registrations: "users/registrations" }

  root "pages#_home"
  get "about" => "pages#about"
  get "love" => "pages#love"
  get "goal-setting-prompts" => "pages#goal-setting-prompts"
  get "heal-with-forgiveness" => "pages#heal-with-forgiveness"
  get "how-to-figure-out-what-you-want" => "pages#how-to-figure-out-what-you-want"
  get "drop-out-of-school" => "pages#drop-out-of-school"
  get "recommended-reading" => "pages#recommended-reading"
  get "self-sabotage" => "pages#self-sabotage"
  get "negativity-detox" => "pages#negativity-detox"
  get "figure-out-your-life" => "pages#figure-out-your-life"
  get "slow-it-down" => "pages#slow-it-down"
  get "negativity-detox-success" => "pages#negativity-detox-success"
  get "foyl-success" => "pages#foyl-success"
  get "/sign_up"   => "devise/registrations#new"
  get "/privacy-policy"   => "pages#privacy-policy"
  get "thank-you" => "pages#thank-you", as: :thank_you
  
  # My Channels
  resources :users
  #get '/users/:id' => 'users#show'

  #mount Commontator::Engine => '/commontator'
  
  get "resources", to: "resources#resources"
  resources :articles, only: [:index, :show]
  resources :courses, only: [:index, :show]

end
end

app/models/article.rb
class Article < Resource
  extend FriendlyId
end

app/models/block.rb
class Block < ActiveRecord::Base
	belongs_to :user

	validates :user_id, :blocked_user_id, presence: true
	validates_uniqueness_of :user_id, scope: :blocked_user_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user

   has_many :pins
end

app/models/channel.rb
class Channel < ActiveRecord::Base
	belongs_to :user

  has_many :pins, dependent: :destroy

  has_attached_file :image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :image

  def self.my_channels(user)
    Channel.where("user_id = ?", user.id)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :pin
end

app/models/course.rb
class Course < Resource
  extend FriendlyId
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  belongs_to :channel
  has_attached_file :image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :image

  validates :image, presence: true
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged 

  has_attached_file :preview_image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :preview_image

  scope :default_order, -> { order(priority: :desc) }
  scope :enabled, -> { where(disabled: false) }
  scope :top, -> { default_order.limit 10 }
end

app/models/resource_page.rb
class ResourcePage < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged 

  has_attached_file :preview_image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }

  scope :default_order, -> { order(order: :asc) }
  scope :enabled, -> { where(disabled: false) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
  has_many :channels
  has_many :blocks

  has_attached_file :image, :styles => { :large => "500x500", :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :image

  validates :name, presence: true

  # Callbacks
  after_create :add_to_mailing_list

  def admin?;admin;end
  private
  def add_to_mailing_list
    Mailchimp::AddToMailingList.subscribe(self)
  end
end

def forem_name
  name
end

app/controllers/forem_controller.rb
class ForemController < ApplicationController
  def base
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    # protect_from_forgery
    before_action :set_pin, only: [:show, :edit, :update, :destroy]
    #before_action :correct_user, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    def index
       @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    end

    def show
      @channel = Channel.find(params[:channel_id])
    end

    def new
        @channel = Channel.find(params[:channel_id])
        @pin = @channel.pins.new
        @pin.user = current_user
    end

    def edit
      @channel = Channel.find(params[:channel_id])
      @pin = Pin.find(params[:id])
    end

    def create
        @channel = Channel.find(params[:channel_id])
        @pin = @channel.pins.new(pin_params)
        @pin.user = current_user
        if @pin.save
          redirect_to channel_pin_path(@channel, @pin), notice: 'Pin was successfully created.'
        else
          render action: 'new'
        end
    end

    def repin_new
      @pin = params[:id]
      @repin = Pin.new
    end

    def repin_create
      pin = Pin.find_by(id: params[:id])
      channel_id = params["pin"]["channel_id"]
      channel = Channel.find_by(id: channel_id)
      repin = pin.dup
      repin.user = current_user
      repin.channel = channel
      repin.image = pin.image
      # respond_to do |format|
        if repin.save
          # format.js { render }
          flash[:notice] = "Your pin was saved to #{channel.name}"
          redirect_to :back
        end
      # end
    end

    def update
        if @pin.update_attributes(pin_params)
            redirect_to channel_pin_path(@pin.channel, @pin), notice: 'Pin was successfully updated.'
        else
           render action: 'edit'
        end
    end

    def destroy
        @channel = Channel.find(params[:channel_id])
        if @pin.destroy
          redirect_to channel_path(@channel)
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
    def set_pin
        @pin = Pin.find(params[:id])
    end

    def correct_user
        @pin = current_user.pins.find_by(id: params[:id])
        redirect_to channel_pin_path(@pin.channel), notice: "Not authorized to edit this pin" if @pin.nil?
    end

    def pin_params
      params.require(:pin).permit(:description, :image, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forem_helper.rb
module ForemHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-app/assets/javascripts lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-app/assets/javascripts lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-app/assets/javascripts lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js"> <!--<![endif]-->
    <head>
    	<script src="//cdn.optimizely.com/js/2350290638.js"></script>
    	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,300,600,700' rel='stylesheet' type='text/css'>
        <meta charset="utf-8">
        
        <title>Resilient: a free mental health app</title>
        <meta name="description" content="Resilient is a free mental health app that's like Pinterest for mental health and provides resources, tips, and inspiration for recovery.">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= javascript_include_tag "application" %>
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
        <%= csrf_meta_tags %>
       
        <%#= stylesheet_link_tag 'application', '../stylesheets/line-icons.min.css' %>
        <%#= stylesheet_link_tag 'application', '../stylesheets/elegant-icons.min.css' %>
        <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-57231916-1', 'auto');
  ga('send', 'pageview');
</script>

<script type="text/javascript">
//<![CDATA[
  (function() {
    var shr = document.createElement('script');
    shr.setAttribute('data-cfasync', 'false');
    shr.src = '//dsms0mj1bbhn4.cloudfront.net/assets/pub/shareaholic.js';
    shr.type = 'text/javascript'; shr.async = 'true';
    shr.onload = shr.onreadystatechange = function() {
      var rs = this.readyState;
      if (rs && rs != 'complete' && rs != 'loaded') return;
      var site_id = '9ae5ae21de943223f289f4d19a387b71';
      try { Shareaholic.init(site_id); } catch (e) {}
    };
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(shr, s);
  })();
//]]>
</script>

<link rel="shortcut icon" href="../images/favicon.ico" type="image/x-icon">
<link rel="icon" href="../images/favicon.ico" type="image/x-icon">

        <!--<script src="../javascripts/modernizr-2.6.2-respond-1.1.0.min.js"></script>-->
    </head>
    <body>
		<div class="nav-container">
			<nav class="top-bar">
				<div class="container">
				
					<!--end of row-->
				
				
					<div class="row nav-menu">
						<div class="col-sm-2 columns logo-top">
							<a href="/">
                <%= image_tag "black-logo-small.gif" %>
								<!--<img alt="Logo" src="../images/white-logo.png">-->
							</a>
						</div>
					
						<div class="col-sm-7 columns">
							<ul class="menu">

        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Browse", channels_path %></li>
        <li><a href="http://blog.resilientapp.com">Blog</a></li>
        <% if user_signed_in? %>
          <li><%= link_to "Profile", user_path(current_user) %></li>
        <% end %>
        <li><a href="http://classes.resilientapp.com/">Classes</a></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>

      </div>
						
						<div class="col-sm-3 columns text-right">
							<ul class="social-icons text-right">
								<li>
									<a href="https://twitter.com/resilientapp">
										<i class="icon social_twitter"></i>
									</a>
								</li>
							
								<li>
									<a href="https://www.facebook.com/resilientapp">
										<i class="icon social_facebook"></i>
									</a>
								</li>
							
								<li>
									<a href="http://www.pinterest.com/resilientapp/">
										<i class="icon social_pinterest"></i>
									</a>
								</li>
								<li>
									<a href="http://resilient-app.tumblr.com/">
										<i class="icon social_tumblr"></i>
									</a>
								</li>
								<li>
									<a href="http://instagram.com/resilient.app">
										<i class="icon social_instagram"></i>
									</a>
								</li>
							</ul>
						</div>
					</div><!--end of row-->
					
					<div class="mobile-toggle">
						<i class="icon icon_menu"></i>
					</div>
					
				</div><!--end of container-->
			</nav>
		
			
		
			
		</div>
<%# flash.each do |name, msg| %>
     <%#= content_tag(:div, msg, class: "alert alert-info") %>
<%# end %>
<%= yield %>


		<div class="footer-container">
			
		
			<footer class="short bg-secondary-1">
				<div class="container">
					<div class="row">
														  <div class="optin">
     <% if user_signed_in? %>
          <div style="width: 40%; float: left; padding: 20px;"><span class="text-white">Get our weekly inspirational emails, and a love letter: "You're Not Broken."</span></div>
          <div id="mc_embed_signup" style="width: 60%; float: left; padding: 20px;"> <form class="validate" id="mc-embedded-subscribe-form" action="//resilientapp.us9.list-manage.com/subscribe/post?u=0f2ed3ea91eb1d8f12d344ee1&amp;id=4334a5a58c" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank"> <div class="mc-field-group"> <input class="required" id="mce-FNAME" type="text" name="FNAME" placeholder="First Name" value=""  /> <input class="required email" id="mce-EMAIL" type="email" name="EMAIL" placeholder="Email Address" value=""  /> <input type="hidden" name="b_8c2fdee11f59dc4d7adf9bcbf_83dec78335" value=""><input type="submit" id="mc-embedded-subscribe" /> </div> </form>
     <% else %>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-white btn-primary" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-filled" %>
  <% end %> <br><br>
  </div></div>
						<br><br><div class="col-sm-8">
				<span class="sub alt-font">

  © Copyright 2014 Resilient, a free mental health app.<br>
								<%= link_to "Account", edit_user_registration_path %> | <%= link_to "About", about_path %> | <%= link_to "Browse", channels_path %> | <%= link_to "Resources", resources_path %> | <%= link_to "Privacy Policy", privacy_policy_path %> | <% if user_signed_in? %>
        <%= link_to "Profile", user_path(current_user) %></li>
        <% end %></span><br><br>
								<span class="sub alt-font">If one of our posts is in violation of your copyright, please <a href="/about.html">contact us</a> and we will remove it.  We're just trying to spread the happiness. :)  This is not medical advice.  If you feel suicidal, call 911 or one of <a href="/channels/10">the suicide hotlines / crisis chats on this page</a>.</span>
							
						</div>
						
						<div class="col-sm-4 text-right">
							<ul class="social-icons text-right">
								<li>
									<a href="https://twitter.com/resilientapp">
										<i class="icon social_twitter"></i>
									</a>
								</li>
							
								<li>
									<a href="https://www.facebook.com/resilientapp">
										<i class="icon social_facebook"></i>
									</a>
								</li>
							
								<li>
									<a href="http://www.pinterest.com/resilientapp/">
										<i class="icon social_pinterest"></i>
									</a>
								</li>
								<li>
									<a href="http://resilient-app.tumblr.com/">
										<i class="icon social_tumblr"></i>
									</a>
								</li>
								<li>
									<a href="http://instagram.com/resilient.app">
										<i class="icon social_instagram"></i>
									</a>
								</li>
							</ul><br><br>

							<a href="https://itunes.apple.com/us/app/resilient/id968678316?ls=1&mt=8"><img src="/images/app-store.png"></a> &nbsp; <a href="https://play.google.com/store/apps/details?id=com.goodbarber.resilient&hl=en"><img src="/images/google-play.gif"></a>
						</div>
					</div><!--end of row-->
				</div><!--end of container-->
			</footer>
		</div>


    <!--<script src="../javascripts/jquery.min.js"></script>-->
    <!--<script src="../javascripts/jquery.plugin.min.js"></script>-->
    <!--<script src="../javascripts/bootstrap.min.js"></script>-->
    <!--<script src="../javascripts/jquery.flexslider-min.js"></script>-->
    <!--<script src="../javascripts/smooth-scroll.min.js"></script>-->
    <!--<script src="../javascripts/skrollr.min.js"></script>-->
    <!--<script src="../javascripts/spectragram.min.js"></script>-->
    <!--<script src="../javascripts/scrollReveal.min.js"></script>-->
    <!--<script src="../javascripts/isotope.min.js"></script>-->
    <!--<script src="../javascripts/twitterFetcher_v10_min.js"></script>-->
    <!--<script src="../javascripts/lightbox.min.js"></script>-->
    <!--<script src="../javascripts/jquery.countdown.min.js"></script>-->
    <!--<script src="../javascripts/scripts.js"></script>-->
    </body>
</html>

app/views/pages/about.html.erb
<div class="main-container">
      <header class="signup"> 
          <div class="background-image-holder parallax-background">
            <img class="background-image" alt="Background Image" src="/images/about.jpg">
          </div>
          
          <div class="container text-center">
              <div class="row text-center">
                <div class="col-sm-12 text-center">
                  <h1 class="text-white">About</h1>
         <% if user_signed_in? %>
          <span class="text-white">Get our weekly inspirational emails, and a love letter: "You're Not Broken."</span><br><br>
          <div id="mc_embed_signup"> <form class="validate" id="mc-embedded-subscribe-form" action="//resilientapp.us9.list-manage.com/subscribe/post?u=0f2ed3ea91eb1d8f12d344ee1&amp;id=4334a5a58c" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank"> <div class="mc-field-group"> <input class="required" id="mce-FNAME" type="text" name="FNAME" placeholder="First Name" value=""  /> <input class="required email" id="mce-EMAIL" type="email" name="EMAIL" placeholder="Email Address" value=""  /> <input type="hidden" name="b_8c2fdee11f59dc4d7adf9bcbf_83dec78335" value=""><input type="submit" id="mc-embedded-subscribe" /> </div> </form>
     <% else %>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-white btn-primary" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-filled" %>
  <% end %> 
                </div>
              </div>
            </div><!--end of container-->
      </header>

     <div class="main-container">
        <div class="row">
          <div class="col-md-1">
            &nbsp;
          </div>
            <div class="col-md-10 row-offset-1 row-offset-2">

<h1>Let's be real. Being depressed sucks. I've been where you are.  I know what it's like.</h1><br><br>

I know because I was depressed for several years before things fell apart in my life and I dropped out of college. I spent a lot of time meditating, contemplating the meaning of existence, and watching marathons of <em>Chopped</em> on the couch before I realized that there wasn't anywhere to go to find helpful resources for dealing with all of this.   It was like crossing an ocean without a map.  So I tried out dozens of different things from many different sources over the course of more than a year before I figured out the tips and tools that were actually helpful.<br><br>

Eventually I figured out what did help and I started to recover.  My good days were more frequent and my bad days were farther apart.  I created a toolbox of resources for dealing with my depressive and anxious moods, everything from meditation to running to cutting out gluten and watching cat videos, and it actually worked.  Recovery is not a one time thing, though.  It's a choice you make every day to rise above your struggle, to say, "This illness does not define me."  And to keep trying.<br><br>

And now?  I'm genuinely happy and in love with life again.  I created Resilient as a mental health app to share inspiration and tips for recovery.  And it's free.  Because regardless of who you are, you deserve to get help, and you deserve to be happy.  Really.<br><br>

Love,<br>
Katie Harp<br>
Founder<br><br>

P.S.  It gets better. <3<br><br>

<img src="/images/profpicbw-200.jpg"><br><br>

katie(at)resilientapp.com<br><br>

</div>
</div>
</div>
</div>

app/views/pages/foyl-success.html.erb
<div class="main-container">
      <header class="signup"> 
          <div class="background-image-holder parallax-background">
            <img class="background-image" alt="Background Image" src="/images/foyl-header.jpg">
          </div>
          
          <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                  <img src="/images/foyl-text.png">
              </div>
            </div>
            </div><!--end of container-->
      </header>

     <div class="main-container">
        <div class="row">
          <div class="col-md-1">
            &nbsp;
          </div>
            <div class="col-md-10 row-offset-1 row-offset-2">

Thanks for signing up for Figure Out Your Life!<br><br>

You will receive your first email within a day or so, and then one each week for the next two weeks (a total of 3 weeks of emails).<br><br>

You rock!  <a href="https://s3-us-west-1.amazonaws.com/resilient-bucket/resources/classes/Figure+Out+Your+Life+Welcome+Message.pdf">Here is a welcome message just for you</a>. :)


</div>
</div>
</div>
</div>
</div>

app/views/pages/thank-you.html.erb
<div class="main-container">
      <header class="signup"> 
          <div class="background-image-holder parallax-background">
            <img class="background-image" alt="Background Image" src="/images/resources.jpg">
          </div>
          
          <div class="container text-center">
              <div class="row text-center">
                <div class="col-sm-12 text-center">
                  <h1 class="text-white">Gee, thanks!</h1>
                </div>
              </div>
            </div><!--end of container-->
      </header>

     <div class="main-container">
        <div class="row">
          <div class="col-md-1">
            &nbsp;
          </div>
            <div class="col-md-10 row-offset-1 row-offset-2">

<h1>Thanks for signing up (you're awesome).</h1><br>

Things are about to get a lot better. :)<br><br>

We'll be sending you an email to confirm our weekly inspirational emails and a love letter, "You're Not Broken."  Please open and confirm. :)<br><br>

You'll want to start by <%= link_to "going to your profile here", user_path(current_user) %> and creating a new channel.  Channels are like boards or categories where you can put a certain type of pin.  Once you create a channel, you can start uploading pins or <%= link_to "browse", channels_path %> around the site and see what other people have posted.

Sit back, relax, and enjoy the journey.

<!-- Facebook Conversion Code for Resilient signups -->
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', '6019037508101', {'value':'0.00','currency':'USD'}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6019037508101&amp;cd[value]=0.00&amp;cd[currency]=USD&amp;noscript=1" /></noscript>

</div>
</div>
</div>
</div>
</div>

app/views/resources/index.html.erb
<div class="main-container">
      <header class="signup"> 
          <div class="background-image-holder parallax-background">
            <img class="background-image" alt="Background Image" src="/images/resources.jpg">
          </div>
          
          <div class="container text-center">
              <div class="row text-center">
                <div class="col-sm-12 text-center">
                  <h1 class="text-white">Resources</h1>
                </div>
              </div>
            </div><!--end of container-->
      </header>

     <div class="main-container">
        <div class="row">
          <div class="col-md-1">
            &nbsp;
          </div>
            <div class="col-md-10 row-offset-1 row-offset-2">

               <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Resilient Main -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-4579984495238903"
     data-ad-slot="9304520911"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script><br><br>

<h1><%= params[:controller].sub("_controller",'') %></h1><br>

<% @resources.each do |r| %>
  <%= link_to r.becomes(r.type.constantize) do %>
    <%= image_tag r.preview_image.url(:medium), alt: r.title, style: "padding: 20px;" %>
  <% end %>
<% end %>
<br><br>
<%= paginate @resources %>

<br><br><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Resilient Main -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-4579984495238903"
     data-ad-slot="9304520911"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

</div>
</div>
</div>
</div>
</div>

app/views/resources/resources.html.erb
<div class="main-container">
      <header class="signup"> 
          <div class="background-image-holder parallax-background">
            <img class="background-image" alt="Background Image" src="/images/resources.jpg">
          </div>
          
          <div class="container text-center">
              <div class="row text-center">
                <div class="col-sm-12 text-center">
                  <h1 class="text-white">Resources</h1>
                </div>
              </div>
            </div><!--end of container-->
      </header>

     <div class="main-container">
        <div class="row">
          <div class="col-md-1">
            &nbsp;
          </div>
            <div class="col-md-10 row-offset-1 row-offset-2">

               <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Resilient Main -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-4579984495238903"
     data-ad-slot="9304520911"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script><br><br>

<h1>Let's get your life back on track.</h1><br>

You're awesome, and we have something for you (ooh presents!).  Below are some resources that we've created to help you in your recovery journey.  Hope you find this helpful!<br><br>

<h3>Shop</h3><br><br>

<% Course.enabled.top.each do |c| %>
  <%= link_to c do %>
    <%= image_tag c.preview_image.url(:medium), alt: c.title, style: "padding: 20px;" %>
  <% end %>
<% end %>
 <a href="/slow-it-down"><img src="/images/sid.jpg" style="padding: 20px;"></a> <a href="/figure-out-your-life"><img src="/images/foyl.jpg" style="padding: 20px;"></a> <a href="/negativity-detox"><img src="/images/30dnd.jpg" style="padding: 20px;"></a> <a href="http://society6.com/resilientstore"><img src="/images/inspirational-prints.jpg" style="padding: 20px;"></a><br>
<br>
<%= link_to("More Classes", courses_path) if Course.enabled.count > 10 %>
<br><br>

<h3>Articles</h3><br><br>

<% Article.enabled.top.each do |a| %>
  <%= link_to a do %>
    <%= image_tag a.preview_image.url(:medium), alt: a.title, style: "padding: 20px;" %>
  <% end %>
<% end %>
<a href="/recommended-reading"><img src="/images/recommended-reading.jpg" style="padding: 20px;"></a> <a href="/goal-setting-prompts"><img src="/images/goal-setting-prompts.jpg" style="padding: 20px;"></a> <a href="/heal-with-forgiveness"><img src="/images/forgiveness-button.jpg" style="padding: 20px;"></a> <a href="/how-to-figure-out-what-you-want"><img src="/images/whatyouwant-button.jpg" style="padding: 20px;"></a> <a href="/drop-out-of-school"><img src="/images/dropout-button.jpg" style="padding: 20px;"></a> <a href="/self-sabotage"><img src="/images/sabotage-button.jpg" style="padding: 20px;"></a>
<br>
<%= link_to("More Articles", articles_path) if Article.enabled.count > 100 %>

<br><br><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Resilient Main -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-4579984495238903"
     data-ad-slot="9304520911"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

</div>
</div>
</div>
</div>
</div>